In [1]:
import torch

In [2]:
torch.cuda.is_available()

False

In [3]:
a=torch.randn(2,3)

In [4]:
type(a)

torch.Tensor

In [5]:
a.type()

'torch.FloatTensor'

In [6]:
idx=torch.randperm(3)

In [7]:
idx

tensor([1, 0, 2])

In [8]:
idx

tensor([1, 0, 2])

In [9]:
a=torch.full([2,2],3)

In [10]:
a

tensor([[3, 3],
        [3, 3]])

In [11]:
b=torch.rsqrt(a)

In [12]:
b

tensor([[0.5774, 0.5774],
        [0.5774, 0.5774]])

In [13]:
c=torch.sqrt(b)

In [14]:
c

tensor([[0.7598, 0.7598],
        [0.7598, 0.7598]])

$$ \text{out}_{i} = \frac{1}{\sqrt{\text{input}_{i}}} $$

In [15]:
g=torch.rand(2,3)*15

In [16]:
g

tensor([[0.4575, 6.1363, 4.4688],
        [6.7055, 3.8208, 1.2909]])

In [17]:
g.max()

tensor(6.7055)

In [18]:
g.median()

tensor(3.8208)

In [19]:
h=g.clamp(g.median())

In [20]:
h

tensor([[3.8208, 6.1363, 4.4688],
        [6.7055, 3.8208, 3.8208]])

In [21]:
a=torch.linspace(-10,10,10)

In [22]:
a

tensor([-10.0000,  -7.7778,  -5.5556,  -3.3333,  -1.1111,   1.1111,   3.3333,
          5.5556,   7.7778,  10.0000])

In [23]:
import torch.nn.functional as F

In [24]:
torch.sigmoid(a)

tensor([4.5398e-05, 4.1877e-04, 3.8510e-03, 3.4445e-02, 2.4766e-01, 7.5234e-01,
        9.6555e-01, 9.9615e-01, 9.9958e-01, 9.9995e-01])

In [25]:
F.sigmoid(a)

C:\Users\ThinkPad\anaconda3\lib\site-packages\torch\nn\functional.py:1805: UserWarning: nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.
  warnings.warn("nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.")


tensor([4.5398e-05, 4.1877e-04, 3.8510e-03, 3.4445e-02, 2.4766e-01, 7.5234e-01,
        9.6555e-01, 9.9615e-01, 9.9958e-01, 9.9995e-01])

In [26]:
b=torch.linspace(-1,1,10)
b

tensor([-1.0000, -0.7778, -0.5556, -0.3333, -0.1111,  0.1111,  0.3333,  0.5556,
         0.7778,  1.0000])

In [27]:
torch.tanh(b)

tensor([-0.7616, -0.6514, -0.5047, -0.3215, -0.1107,  0.1107,  0.3215,  0.5047,
         0.6514,  0.7616])

In [200]:
torch.relu(b)

tensor([0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.1111, 0.3333, 0.5556, 0.7778,
        1.0000])

In [337]:
a=torch.rand(3)

In [338]:
a.requires_grad_()

tensor([0.4800, 0.3387, 0.7037], requires_grad=True)

In [339]:
p=F.softmax(a,dim=0)

In [340]:
p.backward(torch.ones_like(p))

In [341]:
print(p)

tensor([0.3206, 0.2784, 0.4010], grad_fn=<SoftmaxBackward>)


In [206]:
print(a.grad)

tensor([0., 0., 0.])


In [153]:
x = torch.tensor(1.0, requires_grad=True)
y = torch.tensor(2.0, requires_grad=True)
z = x**2+y

In [154]:
z.backward()

In [59]:

print(z, x.grad, y.grad)

tensor(3., grad_fn=<AddBackward0>) tensor(2.) tensor(1.)


In [71]:
torch.autograd.grad(z,x)

(tensor(2.),)

In [257]:
y.grad

In [315]:
c=torch.FloatTensor([1,2,3])

In [316]:
c.requires_grad_()

tensor([1., 2., 3.], requires_grad=True)

In [317]:
y=c**2

In [318]:
torch.autograd.grad(y.sum(),c)

(tensor([2., 4., 6.]),)

In [430]:
c=torch.FloatTensor([1,2,3])
c.requires_grad_()
yy=torch.softmax(c,dim=0)

In [431]:
yy

tensor([0.0900, 0.2447, 0.6652], grad_fn=<SoftmaxBackward>)

In [432]:
yy[0].backward()

In [433]:
c.grad

tensor([ 0.0819, -0.0220, -0.0599])

In [364]:
print(c.grad_fn)

None
